# COLOR GUIDE
# holiday = lightgreen
# deadline = red
# release = pink
# misc = white

events:
  - name: "Code Freeze"
    date: "Jun 3, 2016"
    background: "lightblue"
  - name: "Planned QE Sign-Off"
    date: "Jun 10, 2016"
    background: "white"
  # - name: "8.1 Final Certification"
  #   date: "Dec 18, 2015"
  #   background: "red"
  # - name: "Christmas Eve Holiday!"
  #   date: "Dec 24, 2015"
  #   background: "lightgreen"
  # - name: "Christmas Day Holiday!"
  #   date: "Dec 25, 2015"
  #   background: "lightgreen"
  # - name: "New Year's Holiday!"
  #   date: "Jan 1, 2016"
  #   background: "lightgreen"
  # - name: "MLK Day Holiday!"
  #   date: "Jan 18, 2016"
  #   background: "lightgreen"
  # - name: "President's Day Holiday!"
  #   date: "Feb 15, 2016"
  #   background: "lightgreen"
  # - name: "8.1 Final Available"
  #   date: "Feb 20, 2016"
  #   background: "pink"
  # - name: "Memorial Day Holiday!"
  #   date: "May 30, 2016"
  #   background: "lightgreen"
  # - name: "Independence Day Holiday!"
  #   date: "July 4, 2016"
  #   background: "lightgreen"
  # - name: "Labor Day Holiday!"
  #   date: "Sept 5, 2016"
  #   background: "lightgreen"
  # - name: "Thanksgiving Day Holiday!"
  #   date: "Nov 24, 2016"
  #   background: "lightgreen"
  # - name: "Day After Thanksgiving Holiday!"
  #   date: "Nov 25, 2016"
  #   background: "lightgreen"
  # - name: "Christmas Eve Holiday!"
  #   date: "Dec 23, 2016"
  #   background: "lightgreen"
  # - name: "Christmas Holiday Holiday!"
  #   date: "Dec 26, 2016"
  #   background: "lightgreen"
  # - name: "FedCon"
  #   date: "Feb 20, 2016"
  #   background: "white"
  # - name: "Partner Conference"
  #   date: "March 1, 2016"
  #   background: "white"
  # - name: "Dev Summit"
  #   date: "March 5, 2016"
  #   background: "pink"
  # - name: "UC 2016"
  #   date: "June 20, 2016"
  #   background: "red"